PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

SELECT ?species ?speciesLabel ?taxid ?RefSeq
        WHERE { 
                ?species wdt:P171* wd:Q10876;
                         wdt:P685 ?taxid; wdt:P2249 ?RefSeq.
                SERVICE wikibase:label {
                        bd:serviceParam wikibase:language "en" .
                }
        }
